fix: add new cube iff old cubes move
webgl/2048-cubed pull request #1
Opened 2023-10-10 21:02 UTC by codeocelot

fix bug in moveCubes where new cubes are added even if positions of old cubes do not change. The game we are cloning has the constraint where a new cube is only added if the positions of previous cubes changes.

Two quick fixes:
- first, isEqual needs two objects with the same shape, so there's a new Cube getter to return just x,y,z
- second, each cubes movement needs to be or'd into `moved`-- if any cubes moved, then we need to add a new cube. Using a fancy  [logical or assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment) because it feels perfect for this application (and besides, how often have you seen `||=` in non-compiled js?).
  - if you wanted to get *really* fancy I think you could use DeMorgan's law and flip repeated || !isEqual with repeated && isEqual and flip the output (ie `!moved || !moved || ... === !(moved && moved && ...)`)

PS: I went to, and thoroughly enjoyed, your talk at qcon sf last week.

2023-10-11 17:10 UTC, FarhadG requested changes

2023-10-11 20:13 UTC, codeocelot commented on src/cube.js
> +  get position(){
Amended the commit to add a space char after parens.

```diff
-  get position(){
+  get position() {
```

2023-10-11 20:42 UTC, codeocelot commented
Admittedly, human QA.  I'm a big fan of 2048 as well, while playing it something felt "off".

I also think this project would benefit from a test suite.  You did a great job isolating three to just `Renderer`, DOM manipulation in `Controller` and business logic in `Manager`.

- Manager can probably be tested pretty easily given suitable Controller & Renderer mocks.
- Controller can probably be tested nicely as well, but it would need jsdom or similar.
- Renderer is where testing might get hairy.  Definitely will need to get selenium involved and your three-musketeers project might also be helpful for introspection.  This is the part I'm personally most interested in seeing solved effectively.  

Happy to collab & contribute to this effort.  I guess the first question is, do you have a particular test framework for this project?  Most of the cool kids are using jest so maybe that's a good place to start.

2023-10-26 22:00 UTC, FarhadG commented
> Admittedly, human QA. I'm a big fan of 2048 as well, while playing it something felt "off".
> 
> I also think this project would benefit from a test suite. You did a great job isolating three to just `Renderer`, DOM manipulation in `Controller` and business logic in `Manager`.
> 
> * Manager can probably be tested pretty easily given suitable Controller & Renderer mocks.
> * Controller can probably be tested nicely as well, but it would need jsdom or similar.
> * Renderer is where testing might get hairy.  Definitely will need to get selenium involved and your three-musketeers project might also be helpful for introspection.  This is the part I'm personally most interested in seeing solved effectively.
> 
> Happy to collab & contribute to this effort. I guess the first question is, do you have a particular test framework for this project? Most of the cool kids are using jest so maybe that's a good place to start.

Couldn't agree with you more... I actually have this as a TODO in the README with features I do want to expand upon. Ideally, I'd like to eventually turn this into a book on building an end-to-end game. Would love your contributions.

2023-10-26 22:00 UTC, FarhadG approved these changes

2023-10-26 22:01 UTC, merged